title: Aileen Chen
email: hiaileenchen@gmail.com
description: >- 
  Aileen Chen is a photographer and stylist based in Aotearoa, New Zealand.  
url: aileen-chen.com

# for previewing on github pages
# comment this out when deploying to actual domain
baseurl: /aileen-chen-dot-com

theme-color: white

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"