title: Aileen Chen
email: hiaileenchen@gmail.com
description: >- 
  Aileen Chen is a photographer and stylist based in Aotearoa, New Zealand.  

# for previewing on github pages
# comment this out when deploying to actual domain
# url: heisenburger.github.io
# baseurl: /aileen-chen-dot-com
url: aileen-chen.com

theme-color: white

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"